[phases.setup]
nixPkgs = ["nodejs_22", "pnpm_10"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node --enable-source-maps dist/index.cjs"
