[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["corepack pnpm install --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["corepack pnpm run build"]

[start]
cmd = "node dist/index.cjs"
